extends RefCounted
## The things that live in the world. Fauna is a noun, so it belongs here - what a sheep *is*, not
## whether the game you are playing lets one be sheared.
##
## `base` had no entities at all until 2026-09-23: they went with the games that were deleted, and a
## world you can build in but where nothing moves is a diorama. Thirteen of them, from the models kept
## back because no script can regenerate them - and then four more the same day, the rare ones the
## server is told about, whose models are generated by `tools/box_model.py` and so can be.
##
## **On names, which took some care.** Real animals keep their real names, because a child has to
## recognise a sheep and nobody owns sheep. The invented ones are Quarrowen's own and are deliberately
## not the shapes this genre has made standard - the blob is a marsh creature called a Mirelet, the
## dried-out wanderer is a Dustling, the bowman is a Clatterjack. The Night Stalker, Boomshroom and
## Colossus were this project's inventions already.
##
## **Registered, never spawned.** Not one spawn rule lives here, and the reason is the same one that
## moved the world generator out of `base` earlier the same day: spawn rules attach to the **realm**,
## so a rule written here fires in every world built on `base` - including the Proving Ground's flat
## test world, where mobs appeared, dirtied chunks continuously and stopped a save queue ever
## draining. A pack of nouns that quietly populates every world is not a pack of nouns. What lives
## where is a decision for a game; see `mods/creative/`.



func setup(api) -> void:
	_farm(api)
	_wild(api)
	_monsters(api)
	_rare(api)


## What a meadow has in it. All four are the same shape of creature - wanders, panics, breeds when fed,
## drops something - and differ only in numbers and what they give you, which is the point: a mod that
## adds a fifth writes one dictionary.
func _farm(api) -> void:
	api.register_entity("pig", {"kind": "mob", "display_name": "Pig", "model": "models/pig.glb",
		"width": 0.9, "height": 0.9, "health": 10, "speed": 2.0, "category": "animal", "persistent": true,
		"breeding": {"items": ["base:wheat"], "cooldown": 30.0},
		"drops": [["base:apple", 0, 0.0]],
		"ai": {"preset": "passive", "wander_radius": 8}})
	api.register_entity("sheep", {"kind": "mob", "display_name": "Sheep", "model": "models/sheep.glb",
		"width": 0.9, "height": 1.2, "health": 10, "speed": 1.9, "category": "animal", "persistent": true,
		"breeding": {"items": ["base:wheat"], "cooldown": 30.0},
		# Wool is cloth, and `base` already has sixteen colours of it. A white one, because dyeing is a
		# rule and belongs to whatever game wants to write it.
		"drops": [["base:cloth_white", 1]],
		"ai": {"preset": "passive", "wander_radius": 8}})
	api.register_entity("cow", {"kind": "mob", "display_name": "Cow", "model": "models/cow.glb",
		"width": 1.0, "height": 1.4, "health": 12, "speed": 1.8, "category": "animal", "persistent": true,
		"breeding": {"items": ["base:wheat"], "cooldown": 40.0},
		"ai": {"preset": "passive", "wander_radius": 8}})
	api.register_entity("chicken", {"kind": "mob", "display_name": "Chicken", "model": "models/chicken.glb",
		"width": 0.5, "height": 0.7, "health": 4, "speed": 1.6, "category": "animal", "persistent": true,
		"breeding": {"items": ["base:wheat_seeds"], "cooldown": 30.0},
		"ai": {"preset": "passive", "wander_radius": 10}})


## Animals that can look after themselves. Both are `neutral`: they leave you alone until you do not.
func _wild(api) -> void:
	api.register_entity("wolf", {"kind": "mob", "display_name": "Wolf", "model": "models/wolf.glb",
		"width": 0.7, "height": 0.9, "health": 14, "speed": 3.4, "category": "animal", "persistent": true,
		# Tameable, because a child with a dog is a different game from a child without one, and the
		# engine already has the capability. What it does once tamed is the game's business.
		"taming": {"items": ["base:apple"], "chance": 0.35, "follow_distance": 3.0, "teleport_distance": 16.0},
		"nameplate": {"show_health": true},
		"ai": {"preset": "neutral", "aggression": 0.6, "wander_radius": 14}})
	api.register_entity("spider", {"kind": "mob", "display_name": "Spider", "model": "models/spider.glb",
		"width": 1.1, "height": 0.7, "health": 12, "speed": 3.0, "category": "monster",
		# Wide and low, and it climbs a step it has no business climbing - which is most of what makes
		# a spider feel like a spider rather than a fast pig.
		"ai": {"preset": "neutral", "aggression": 0.5, "step_up": 2, "wander_radius": 12}})


## The night shift. Named and shaped as this world's own; see the note at the top of the file.
func _monsters(api) -> void:
	api.register_entity("dustling", {"kind": "mob", "display_name": "Dustling", "model": "models/zombie.glb",
		"width": 0.7, "height": 1.8, "health": 18, "speed": 1.9, "category": "monster",
		# Slow, patient and it hunts in company: the threat is being surrounded, not being outrun.
		"ai": {"preset": "hostile", "aggression": 0.7, "courage": 1.0, "pack": true, "sight_range": 18.0}})
	api.register_entity("clatterjack", {"kind": "mob", "display_name": "Clatterjack", "model": "models/skeleton.glb",
		"width": 0.7, "height": 1.8, "health": 14, "speed": 2.2, "category": "monster",
		# Keeps its distance and shoots, so the answer is cover rather than running at it.
		"ai": {"preset": "archer"}})
	api.register_entity("mirelet", {"kind": "mob", "display_name": "Mirelet", "model": "models/slime.glb",
		"width": 0.8, "height": 0.8, "health": 8, "speed": 1.4, "category": "monster",
		# A marsh thing. Weak, slow and never alone, which is a different problem from a strong one.
		"ai": {"preset": "hostile", "aggression": 0.5, "courage": 1.0, "intelligence": 0.2,
			"jump": true, "wander_radius": 6}})
	api.register_entity("night_stalker", {"kind": "mob", "display_name": "Night Stalker",
		"model": "models/night_stalker.glb",
		"width": 0.8, "height": 2.2, "health": 26, "speed": 3.6, "category": "monster",
		# Fast, brave and it sees a long way. The one you do not want to meet in the open.
		"ai": {"preset": "hostile", "aggression": 0.85, "courage": 1.0, "intelligence": 0.8,
			"sight_range": 28.0}})
	api.register_entity("boomshroom", {"kind": "mob", "display_name": "Boomshroom",
		"model": "models/boomshroom.glb",
		"width": 0.8, "height": 1.4, "health": 10, "speed": 1.6, "category": "monster",
		# It walks up to you and goes off. The explosion itself is a rule - whether it breaks blocks is
		# the `mob_griefing` setting - so all this says is that the creature exists and is nervous.
		"ai": {"preset": "hostile", "aggression": 0.9, "courage": 1.0, "intelligence": 0.3}})
	api.register_entity("goblin", {"kind": "mob", "display_name": "Goblin", "model": "models/goblin.glb",
		"width": 0.6, "height": 1.2, "health": 12, "speed": 3.2, "category": "monster",
		# Quick, cowardly, and it runs when it is losing - which teaches a child that not everything
		# fights to the death.
		"ai": {"preset": "hostile", "aggression": 0.6, "courage": 0.3, "agility": 0.7}})
	# A boss is an event a game arranges, not weather - and like everything here it is registered only.
	# because the model and the creature are nouns and a game should not have to invent them.
	api.register_entity("colossus", {"kind": "mob", "display_name": "Ancient Colossus",
		"model": "models/colossus.glb",
		"width": 1.2, "height": 7.2, "health": 300, "speed": 2.4, "category": "monster",
		"nameplate": {"show_health": true},
		"ai": {"preset": "boss"}})


## The four you are told about.
##
## **What makes these different is `notable`, and that is an engine capability rather than a trick
## here**: the server says a line in chat when one appears, puts a marker on everybody's map and
## compass that *follows* it, counts down how long is left on the marker's own label, and takes the
## creature away again when the time runs out. All this file decides is which creatures are worth it
## and what they say. See `engine/server/sightings.gd`.
##
## **Ten minutes, because a hunt needs a clock.** Without one the creature stands where it spawned
## until somebody wanders past, the compass needle stops meaning "go now", and a week of nights piles
## them up on the map. (the user, 2026-09-23)
##
## **Mild, and that word was doing real work.** These are night things for children: they are strange
## and a bit frightening to meet, and nothing about them is gory or cruel. The folklore they come from
## is old and belongs to nobody - a light that leads travellers off the path, a piper, a thing asleep
## under a burial mound, a moth that finds the window - and none of it is the shape this genre has
## made standard. The Palemoth cannot hurt you at all, which is the point of having four rather than
## three: the youngest child gets one to hunt too.
##
## **Registered, never spawned**, like everything else here - see the note at the top of the file.
func _rare(api) -> void:
	# What the night leaves behind. Here rather than with the ores because each one is the reason to go
	# after a particular creature, and a curio filed away from the thing that drops it is a curio
	# nobody connects to anything. What they are *for* is a game's business: `base` says they exist.
	api.register_item("emberheart", {"group": "Curios", "display_name": "Emberheart",
		"icon": "textures/emberheart.png", "max_stack": 16, "glow": {"color": "#ffb45a", "energy": 0.7}})
	api.register_item("moonpearl", {"group": "Curios", "display_name": "Moonpearl",
		"icon": "textures/moonpearl.png", "max_stack": 16})
	api.register_item("hollow_reed", {"group": "Curios", "display_name": "Hollow Reed",
		"icon": "textures/hollow_reed.png", "max_stack": 16})
	api.register_item("warden_core", {"group": "Curios", "display_name": "Warden Core",
		"icon": "textures/warden_core.png", "max_stack": 16})

	# Loot **tables** rather than a `drops` list, and the difference is worth the four extra lines: a
	# table has real weights, so the engine knows which entry was the unlikely one. It sparkles where it
	# fell, makes a noise, says so in chat, and a run of bad luck eventually pays out anyway (see
	# LootRegistry - `chance_of`, and the pity rolls). A flat `drops` list gets none of that.
	api.register_loot("wisp_loot", {"pools": [
		{"rolls": 1, "guaranteed": true, "entries": [{"item": "base:emberheart", "count": [1, 2]}]},
		{"rolls": 2, "entries": [
			{"item": "base:sunstone", "count": [1, 2], "weight": 6},
			{"item": "base:gold_ingot", "count": [1, 3], "weight": 3},
			{"item": "base:coal", "count": [1, 4], "weight": 8}]}]})
	api.register_loot("piper_loot", {"pools": [
		{"rolls": 1, "guaranteed": true, "entries": [{"item": "base:hollow_reed", "count": [1, 1]}]},
		{"rolls": 2, "entries": [
			{"item": "base:gold_ingot", "count": [2, 4], "weight": 5},
			{"item": "base:cobalt_ingot", "count": [1, 2], "weight": 2},
			{"item": "base:iron_ingot", "count": [2, 5], "weight": 8}]}]})
	api.register_loot("warden_loot", {"pools": [
		{"rolls": 1, "guaranteed": true, "entries": [{"item": "base:warden_core", "count": [1, 1]}]},
		{"rolls": 3, "entries": [
			{"item": "base:cobalt_ingot", "count": [1, 3], "weight": 4},
			{"item": "base:sunstone", "count": [1, 2], "weight": 2},
			{"item": "base:iron_ingot", "count": [3, 6], "weight": 9},
			{"item": "base:gold_ingot", "count": [1, 3], "weight": 6}]}]})
	api.register_loot("palemoth_loot", {"pools": [
		{"rolls": 1, "guaranteed": true, "entries": [{"item": "base:moonpearl", "count": [1, 2]}]},
		{"rolls": 1, "entries": [
			{"item": "base:cloth_white", "count": [1, 3], "weight": 8},
			{"item": "base:sunstone", "count": [1, 1], "weight": 1}]}]})

	# A light that will not be caught. `gravity: 0` is what makes it drift rather than walk, and it is
	# quick and brave enough to stay ahead of you - so the hunt is the chase, not the fight.
	api.register_entity("wisp", {"kind": "mob", "display_name": "Wisp", "model": "models/wisp.glb",
		"width": 0.5, "height": 0.7, "health": 12, "speed": 5.0, "category": "monster",
		"glow": true, "gravity": 0.0, "drag": 1.2, "persistent": true, "loot": "base:wisp_loot",
		"notable": {"announce": "A Wisp is drifting somewhere out in the dark.",
			"slain": "%s caught the Wisp!", "gone": "The Wisp has faded out.",
			"color": "#9fe4ff", "minutes": 10},
		"ai": {"preset": "neutral", "aggression": 0.2, "courage": 0.2, "agility": 0.9,
			"wander_radius": 20}})
	# Tall, slow and it never stops. Nothing about it is fast or loud; the whole idea is that walking
	# away works and standing still does not.
	api.register_entity("hollow_piper", {"kind": "mob", "display_name": "Hollow Piper",
		"model": "models/hollow_piper.glb",
		"width": 0.6, "height": 2.6, "health": 40, "speed": 1.5, "category": "monster",
		"knockback_resistance": 0.8, "persistent": true, "loot": "base:piper_loot",
		"nameplate": {"show_health": true},
		"notable": {"announce": "A Hollow Piper is walking somewhere tonight.",
			"slain": "%s saw off the Hollow Piper.", "gone": "The piping has stopped.",
			"color": "#cdc3ad", "minutes": 10},
		"ai": {"preset": "hostile", "aggression": 0.8, "courage": 1.0, "intelligence": 0.9,
			"sight_range": 32.0}})
	# Old stone that gets up. Slow, very hard to move and it hits like the hill it was part of.
	api.register_entity("barrow_warden", {"kind": "mob", "display_name": "Barrow Warden",
		"model": "models/barrow_warden.glb",
		"width": 1.1, "height": 2.4, "health": 80, "speed": 1.7, "category": "monster",
		"knockback_resistance": 1.0, "persistent": true, "loot": "base:warden_loot",
		"nameplate": {"show_health": true},
		"notable": {"announce": "A Barrow Warden has woken up.",
			"slain": "%s laid the Barrow Warden back down.", "gone": "The Barrow Warden has gone back to sleep.",
			"color": "#8fae6a", "minutes": 10},
		"ai": {"preset": "hostile", "aggression": 0.7, "courage": 1.0, "intelligence": 0.4,
			"step_up": 2, "sight_range": 16.0}})
	# The one that cannot hurt anybody. It is rare, it is beautiful, it runs away, and it is worth more
	# than most of what will try to eat you - so a child who does not want to fight anything still has
	# something to go out at night for.
	api.register_entity("palemoth", {"kind": "mob", "display_name": "Palemoth",
		"model": "models/palemoth.glb",
		"width": 1.2, "height": 0.9, "health": 8, "speed": 4.2, "category": "animal",
		"gravity": 6.0, "drag": 0.6, "persistent": true, "loot": "base:palemoth_loot",
		"notable": {"announce": "A Palemoth is about. It will not hurt you.",
			"slain": "%s caught the Palemoth.", "gone": "The Palemoth has gone.",
			"color": "#f4eee1", "minutes": 10},
		"ai": {"preset": "passive", "agility": 1.0, "jump": true, "wander_radius": 18}})
