extends RefCounted
## What a player sees and hears: effects, beams, decals, screen tints, nameplates, floating words,
## panels, music, weather, milestones and the guidebook.

var api
var ids: Dictionary


func setup(mod_api, id_table: Dictionary) -> void:
	api = mod_api
	ids = id_table
	_setup_music()
	api.register_effect("puff", {"particles": 12, "color": "#cccccc", "scale": 1.0, "duration": 0.6})
	api.register_weather("haze", {"display_name": "Haze", "darkness": 0.2, "particles": "puff"})
	api.register_weather("downpour", {"display_name": "Downpour", "darkness": 0.45, "particles": "puff", "rain": true})
	# Weather and wind are separate on purpose - a still downpour is a real thing - so a mod that wants
	# a gale with its storm says so. Visual only: nothing in the simulation reads it.
	api.on("weather_changed", func(ev):
		if String(ev.get("weather", "")) == "proving:downpour":
			api.set_wind(240.0, 0.85)
		else:
			api.set_wind(135.0, 0.25))
	# A cosmetic, which is its own registry and had no other user left.
	api.register_cosmetic("cap", {"category": "hat", "display_name": "Cap", "unlocked": true,
		"boxes": [{"from": [-4, 8, -4], "size": [8, 2, 8], "color": "#4488cc"}]})
	api.register_milestone("first_stone", {"display_name": "First Stone",
		"goal": {"type": "break", "target": ["proving:rock"]}})
	# A tutorial, because tutorials are a capability and nothing else exercises them now.
	api.register_tutorial("basics", {"display_name": "Basics", "auto_start": true, "order": 1,
		"modes": ["survival"], "steps": [
		{"title": "Find a rock", "goal": {"type": "break", "target": ["proving:rock"]}},
		{"title": "Hold four", "goal": {"type": "have", "target": ["proving:rock"], "count": 4}},
		{"title": "Say when", "goal": {"type": "manual"}}]})
	# A second tutorial and a tip, so ordering and the tip rules have something to act on.
	# The creative one, because a player who cannot dig still needs telling how to look around.
	api.register_tutorial("controls", {"display_name": "Controls", "order": 2, "auto_start": true,
		"modes": ["creative"], "steps": [
		{"title": "Look around", "text": "W A S D to walk, the mouse to look.", "goal": {"type": "manual"}}]})
	api.register_tip("basics", {"text": "Rock is the thing to dig", "trigger": {"type": "night"}})
	api.register_guide_chapter("proving", {"title": "The Proving Ground", "order": 1})
	api.register_guide_page("what", {"chapter": "proving", "title": "What this is",
		"content": [{"type": "text", "text": "A mod that exists to be tested."}]})
	# Damage numbers, which is float_text plus the post-damage event in one.
	api.on("entity_damaged", func(ev):
		var e = ev.entity
		var was := float(e.data.get("_shown", ev.health))
		e.data["_shown"] = float(ev.health)
		if was - float(ev.health) >= 0.5:
			api.float_text("%d" % roundi(was - float(ev.health)),
				e.body.position + Vector3(0, e.def.height * 0.9, 0),
				{"color": "#ffd166", "follow": e, "seconds": 0.8}))
	# A panel in a corner, which is the whole of "mod-defined corners of the interface".
	api.register_command("panel", "Show a corner panel", func(player, _args):
		player.show_ui("proving:corner", {"anchor": "top_right", "children": [
			{"type": "label", "text": "Proving Ground", "size": 16},
			{"type": "progress", "value": int(api.balance_of(player, "coins")), "max": 10, "color": "#6fcf97"},
			{"type": "button", "text": "Close", "action": "close"}]}))
	api.register_command("effects", "Fire one of everything", func(player, _args):
		var at: Vector3 = player.position
		api.play_effect("puff", at + Vector3(0, 1, 0), {"scale": 1.0})
		api.play_beam(at + Vector3(0, 1, 0), at + Vector3(0, 1, 6), {"color": "#88ddff", "seconds": 0.5})
		api.play_decal(at - Vector3(0, 0.5, 0), Vector3i.UP, {"color": "#222222", "size": 2.0})
		api.screen_tint(player, {"color": "#3366aa", "strength": 0.3})
		api.float_text("hello", at + Vector3(0, 2, 0), {"color": "#ffffff"}))


## The music lane, which is the only content that deliberately does *not* join the download a player
## waits through to get in. It arrives afterwards and starts when it is ready.
##
## Here because nothing else covers it: the two tracks used to live in the sandbox game, and when the
## games went the e2e music assertions went with them - they were gated on `--game=vanilla`, so they
## stopped running rather than started failing, which is the worse of the two. (2026-09-21)
##
## Two tracks, not one, because a list with a single entry cannot prove the server *chose*. On the
## crossing rather than on a stopwatch, and on join as well: somebody arriving at midnight has to hear
## the night track now, not when the sun next comes up.
func _setup_music() -> void:
	var credit := "Quarrowen placeholder, generated by tools/generate_music.py (CC0)"
	api.register_music("daylight", "music/daylight.ogg", {"volume": 0.9, "attribution": credit})
	api.register_music("night", "music/night.ogg", {"volume": 0.9, "attribution": credit})
	api.on("time_changed", func(ev): api.play_music(null, "night" if ev.phase == "night" else "daylight", {"fade": 6.0}))
	api.on("player_join", func(ev):
		api.play_music(ev.player, "night" if api.get_daylight() < 0.3 else "daylight", {"fade": 6.0}))
