extends RefCounted
## Vanilla structures: dungeons with spawners, ruins and watchtowers built from local materials,
## branching mineshafts, and the rare ancient arena where the Colossus waits. Templates live in
## structures/ (generated by tools/generate_structures.py, or rebuild them in game with /struct save).

const CORRIDORS := [["mineshaft_corridor", 0.75], ["mineshaft_corridor_chest", 0.13], ["mineshaft_corridor_webs", 0.12]]

var api
var ids := {}


func setup(mod_api) -> void:
	api = mod_api
	var soft := {"break": "base:grass", "place": "base:grass", "step": "base:soft_step"}
	api.register_block("cobweb", {"display_name": "Cobweb", "textures": "textures/cobweb.png", "render": "plant", "solid": false,
		"replaceable": false, "hardness": 1.0, "drops": "vanilla:string", "sounds": soft})
	ids.altar = api.register_block("ancient_altar", {"display_name": "Ancient Altar", "textures": "textures/ancient_altar.png", "light": 6,
		"hardness": 50.0, "tier": 3, "tool": "pickaxe", "drops": "", "sounds": {"break": "base:stone", "place": "base:stone", "step": "base:stone_step"}})
	api.register_block_tick("vanilla:ancient_altar", _altar_tick, {"interval": 3.0, "catch_up": false})
	_loot()
	for template in ["dungeon", "ruin_small", "ruin_long", "watchtower", "mineshaft_corridor", "mineshaft_corridor_chest",
			"mineshaft_corridor_webs", "mineshaft_crossing", "mineshaft_room", "colossus_arena"]:
		api.register_structure_template(template, "structures/%s.json" % template)
	# Surface buildings use what grows nearby.
	var swaps := {
		"vanilla:desert": {"base:cobblestone": "base:sandstone", "base:planks": "base:sandstone", "base:log": "base:sandstone"},
		"vanilla:taiga": {"base:log": "base:spruce_log"}, "vanilla:snowy_tundra": {"base:log": "base:spruce_log"},
		"vanilla:savanna": {"base:log": "base:acacia_log"}, "vanilla:birch_forest": {"base:log": "base:birch_log"},
		"vanilla:shadowwood": {"base:log": "vanilla:shadow_log"},
	}
	api.register_structure("dungeon", {"templates": [{"template": "dungeon"}], "place": "underground", "y": [8, 40],
		"spacing": 5, "separation": 1, "chance": 0.8})
	api.register_structure("ruins", {"templates": [{"template": "ruin_small"}, {"template": "ruin_long"}], "place": "surface", "sink": 1,
		"spacing": 12, "separation": 3, "chance": 0.7, "swaps": swaps,
		"biomes": ["vanilla:plains", "vanilla:forest", "vanilla:birch_forest", "vanilla:savanna", "vanilla:desert", "vanilla:taiga",
			"vanilla:snowy_tundra", "vanilla:swamp", "vanilla:shadowwood"]})
	api.register_structure("watchtower", {"templates": [{"template": "watchtower"}], "place": "surface", "foundation": "base:cobblestone",
		"spacing": 20, "separation": 5, "chance": 0.7, "swaps": swaps,
		"biomes": ["vanilla:plains", "vanilla:savanna", "vanilla:desert", "vanilla:taiga", "vanilla:snowy_tundra"]})
	api.register_structure("mineshaft", {"generator": _mineshaft, "place": "underground", "y": [18, 34], "spacing": 10, "separation": 2,
		"chance": 0.7, "reach": 6})
	api.register_structure("colossus_arena", {"templates": [{"template": "colossus_arena"}], "place": "surface", "foundation": "base:cobblestone",
		"spacing": 48, "separation": 12, "chance": 0.6, "reach": 2, "biomes": ["vanilla:plains", "vanilla:savanna", "vanilla:desert"]})


func _loot() -> void:
	api.register_loot_table("dungeon", {"rolls": [3, 6], "entries": [
		{"item": "base:bread", "count": [1, 3], "weight": 3}, {"item": "base:iron_ingot", "count": [1, 4], "weight": 3},
		{"item": "vanilla:bone", "count": [2, 6], "weight": 3}, {"item": "vanilla:string", "count": [1, 4], "weight": 2},
		{"item": "base:coal", "count": [2, 8], "weight": 2}, {"item": "vanilla:bucket", "count": [1, 1], "weight": 1},
		{"item": "base:workbench_plans", "count": [1, 1], "weight": 0.6}, {"item": "base:forge_plans", "count": [1, 1], "weight": 0.4},
		{"item": "base:cobalt_ingot", "count": [1, 2], "weight": 0.5}]})
	api.register_loot_table("ruins", {"rolls": [2, 4], "entries": [
		{"item": "base:coal", "count": [1, 5], "weight": 3}, {"item": "base:wheat_seeds", "count": [2, 6], "weight": 3},
		{"item": "base:apple", "count": [1, 3], "weight": 2}, {"item": "base:iron_ingot", "count": [1, 2], "weight": 1},
		{"item": "base:torch", "count": [2, 6], "weight": 2}]})
	api.register_loot_table("watchtower", {"rolls": [3, 5], "entries": [
		{"item": "base:bread", "count": [2, 4], "weight": 3}, {"item": "base:iron_ingot", "count": [2, 5], "weight": 2},
		{"item": "vanilla:shears", "count": [1, 1], "weight": 1}, {"item": "vanilla:steak", "count": [1, 3], "weight": 2},
		{"item": "base:iron_sword", "count": [1, 1], "weight": 0.5}, {"item": "base:workbench_plans", "count": [1, 1], "weight": 0.5}]})
	api.register_loot_table("mineshaft", {"rolls": [2, 5], "entries": [
		{"item": "base:coal", "count": [3, 9], "weight": 3}, {"item": "base:iron_ore", "count": [1, 5], "weight": 3},
		{"item": "base:cobalt_ore", "count": [1, 2], "weight": 1}, {"item": "base:bread", "count": [1, 3], "weight": 2},
		{"item": "base:torch", "count": [4, 12], "weight": 2}]})
	api.register_loot_table("arena", {"rolls": [4, 7], "entries": [
		{"item": "base:cobalt_ingot", "count": [2, 5], "weight": 3}, {"item": "base:iron_ingot", "count": [4, 10], "weight": 3},
		{"item": "vanilla:shadow_essence", "count": [1, 2], "weight": 1}, {"item": "base:forge_plans", "count": [1, 1], "weight": 1},
		{"item": "vanilla:steak", "count": [3, 6], "weight": 2}]})


## Mineshafts: a dirt-floored room with corridors wandering out of each side, branching at crossings.
func _mineshaft(origin: Vector3i, rng: RandomNumberGenerator, _structures) -> Array:
	var pieces := [{"template": "vanilla:mineshaft_room", "position": origin - Vector3i(4, 0, 4), "rotation": 0}]
	var floor_y := origin.y
	var budget := [36]
	for dir in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
		if rng.randf() < 0.8:
			_corridor(pieces, Vector2i(origin.x, origin.z) + dir * 5, dir, floor_y, rng, 5, budget, Vector2i(origin.x, origin.z))
	return pieces


func _corridor(pieces: Array, head: Vector2i, dir: Vector2i, y: int, rng: RandomNumberGenerator, depth: int, budget: Array, origin: Vector2i) -> void:
	var length := rng.randi_range(2, 6)
	for i in length:
		if budget[0] <= 0 or (head - origin).length() > 70:
			return
		budget[0] -= 1
		pieces.append({"template": "vanilla:" + _pick_corridor(rng), "position": _corridor_corner(head, dir, y), "rotation": _rotation(dir)})
		head += dir * 5
	if depth <= 0 or budget[0] <= 0:
		return
	# A crossing, then carry on and maybe branch sideways.
	var center := head + dir * 2
	pieces.append({"template": "vanilla:mineshaft_crossing", "position": Vector3i(center.x - 2, y, center.y - 2), "rotation": 0})
	budget[0] -= 1
	_corridor(pieces, center + dir * 3, dir, y, rng, depth - 1, budget, origin)
	for side in [Vector2i(dir.y, -dir.x), Vector2i(-dir.y, dir.x)]:
		if rng.randf() < 0.45:
			_corridor(pieces, center + side * 3, side, y, rng, depth - 2, budget, origin)


func _pick_corridor(rng: RandomNumberGenerator) -> String:
	var roll := rng.randf()
	for entry in CORRIDORS:
		roll -= float(entry[1])
		if roll <= 0.0:
			return entry[0]
	return CORRIDORS[0][0]


## Corridor templates run along +X, 5 long and 3 wide; turn and shift them to start at `head` heading `dir`.
func _corridor_corner(head: Vector2i, dir: Vector2i, y: int) -> Vector3i:
	if dir == Vector2i(1, 0):
		return Vector3i(head.x, y, head.y - 1)
	if dir == Vector2i(-1, 0):
		return Vector3i(head.x - 4, y, head.y - 1)
	if dir == Vector2i(0, 1):
		return Vector3i(head.x - 1, y, head.y)
	return Vector3i(head.x - 1, y, head.y - 4)


func _rotation(dir: Vector2i) -> int:
	if dir == Vector2i(1, 0):
		return 0
	if dir == Vector2i(0, 1):
		return 1
	if dir == Vector2i(-1, 0):
		return 2
	return 3


## The arena's altar wakes the Colossus once, when a player comes close.
func _altar_tick(ctx: Dictionary) -> void:
	var pos: Vector3i = ctx.position
	var data: Dictionary = api.get_block_data(pos)
	if not (data.get("boss") is Dictionary) or data.boss.get("spawned", false):
		return
	for player in api.get_players():
		if player.position.distance_to(Vector3(pos)) < 12.0 and not player.is_creative():
			data.boss.spawned = true
			api.set_block_data(pos, data)
			var boss = api.spawn_entity(str(data.boss.entity), Vector3(pos) + Vector3(0.5, 0.0, 6.5), {"yaw": PI})
			if boss != null:
				boss.set_home(boss.position, 20.0)
				api.play_sound("vanilla:colossus_roar", boss.position)
				api.broadcast("The Ancient Colossus rises from the arena floor!")
			return
