#!/usr/bin/env bash
# Rebuilds Firstlight's character models from their box specs.
#
#   mods/firstlight/models/build.sh
#
# **The spec lives here because nowhere else was keeping it.** Every other `.glb` in the tree was
# generated by a one-off `box_model.py` command line and then committed, so the only record of how a
# model was built was the shell history of whoever built it. That cost an afternoon on Wick: his
# lantern's boxes had been written relative to its pivot instead of in model coordinates, which put
# the glowing part *below his feet* and centred on his body rather than in his hand - and with no
# source to read, the symptom (a pool of light on the grass) looked like a rendering problem rather
# than a typo. (2026-09-24)
#
# Coordinates are in blocks, y up, and the model faces -Z. Boxes are always in **model** coordinates,
# including the ones after an `@part:pivot` - the pivot only says what the part rotates around.
set -euo pipefail
cd "$(dirname "$0")/../../.."

python3 tools/box_model.py mods/firstlight/models/wick.glb \
  @body:0,0,0 \
    -0.16,1.06,-0.14,0.16,1.32,0.14,#d9ab82 \
    -0.11,1.16,-0.16,-0.04,1.22,-0.13,#2a2118 \
    0.04,1.16,-0.16,0.11,1.22,-0.13,#2a2118 \
    -0.25,1.30,-0.23,0.25,1.36,0.23,#3b2c1d \
    -0.13,1.36,-0.11,0.13,1.50,0.11,#4a3826 \
  @coat:0,0,0 \
    -0.20,0.55,-0.13,0.20,1.06,0.13,#8a6a45 \
    -0.24,0.55,-0.16,0.24,0.74,0.16,#6f5436 \
    -0.21,0.86,-0.14,0.21,0.94,0.14,#c8a05a \
  @leg_a:-0.1,0.56,0 \
    -0.17,0.00,-0.08,-0.03,0.56,0.08,#3f3128 \
  @leg_b:0.1,0.56,0 \
    0.03,0.00,-0.08,0.17,0.56,0.08,#3f3128 \
  @arm_a:-0.23,0.99,0 \
    -0.30,0.56,-0.08,-0.16,1.00,0.08,#8a6a45 \
  @lantern:-0.23,0.56,0 \
    -0.30,0.50,-0.07,-0.16,0.55,0.07,#5a4a2a \
    -0.32,0.30,-0.09,-0.14,0.50,0.09,#ffc65a! \
    -0.30,0.26,-0.07,-0.16,0.30,0.07,#5a4a2a \
  @arm_b:0.23,0.99,0 \
    0.16,0.56,-0.08,0.30,1.00,0.08,#8a6a45

echo "wrote mods/firstlight/models/wick.glb"
